// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package spairego

import (
	"github.com/Spaire-Tech/spaire-go/internal/config"
	"github.com/Spaire-Tech/spaire-go/internal/hooks"
)

type CustomerPortal struct {
	BenefitGrants   *SpaireBenefitGrants
	Customers       *SpaireCustomers
	CustomerMeters  *SpaireCustomerMeters
	Seats           *Seats
	CustomerSession *CustomerSession
	Downloadables   *Downloadables
	LicenseKeys     *SpaireLicenseKeys
	Members         *SpaireMembers
	Orders          *SpaireOrders
	Organizations   *SpaireOrganizations
	Subscriptions   *SpaireSubscriptions
	Wallets         *Wallets

	rootSDK          *Spaire
	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

func newCustomerPortal(rootSDK *Spaire, sdkConfig config.SDKConfiguration, hooks *hooks.Hooks) *CustomerPortal {
	return &CustomerPortal{
		rootSDK:          rootSDK,
		sdkConfiguration: sdkConfig,
		hooks:            hooks,
		BenefitGrants:    newSpaireBenefitGrants(rootSDK, sdkConfig, hooks),
		Customers:        newSpaireCustomers(rootSDK, sdkConfig, hooks),
		CustomerMeters:   newSpaireCustomerMeters(rootSDK, sdkConfig, hooks),
		Seats:            newSeats(rootSDK, sdkConfig, hooks),
		CustomerSession:  newCustomerSession(rootSDK, sdkConfig, hooks),
		Downloadables:    newDownloadables(rootSDK, sdkConfig, hooks),
		LicenseKeys:      newSpaireLicenseKeys(rootSDK, sdkConfig, hooks),
		Members:          newSpaireMembers(rootSDK, sdkConfig, hooks),
		Orders:           newSpaireOrders(rootSDK, sdkConfig, hooks),
		Organizations:    newSpaireOrganizations(rootSDK, sdkConfig, hooks),
		Subscriptions:    newSpaireSubscriptions(rootSDK, sdkConfig, hooks),
		Wallets:          newWallets(rootSDK, sdkConfig, hooks),
	}
}
