// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"app.spairehq.com/go/models/components"
)

type ClientInvoicesCreateClientInvoiceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ClientInvoiceSchema *components.ClientInvoiceSchema
}

func (c *ClientInvoicesCreateClientInvoiceResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClientInvoicesCreateClientInvoiceResponse) GetClientInvoiceSchema() *components.ClientInvoiceSchema {
	if c == nil {
		return nil
	}
	return c.ClientInvoiceSchema
}
