// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"app.spairehq.com/go/models/components"
)

type ClientInvoicesDownloadClientInvoicePdfRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (c *ClientInvoicesDownloadClientInvoicePdfRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

type ClientInvoicesDownloadClientInvoicePdfResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (c *ClientInvoicesDownloadClientInvoicePdfResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}
