// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"app.spairehq.com/go/models/components"
)

type ClientInvoicesPreviewClientInvoicePdfResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (c *ClientInvoicesPreviewClientInvoicePdfResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}
