// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"app.spairehq.com/go/internal/utils"
	"app.spairehq.com/go/models/components"
)

type ClientInvoicesListClientInvoicesRequest struct {
	// Page number, defaults to 1.
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Size of a page, defaults to 10. Maximum is 100.
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
	Sorting []components.ClientInvoiceSortProperty `queryParam:"style=form,explode=true,name=sorting"`
}

func (c ClientInvoicesListClientInvoicesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientInvoicesListClientInvoicesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientInvoicesListClientInvoicesRequest) GetPage() *int64 {
	if c == nil {
		return nil
	}
	return c.Page
}

func (c *ClientInvoicesListClientInvoicesRequest) GetLimit() *int64 {
	if c == nil {
		return nil
	}
	return c.Limit
}

func (c *ClientInvoicesListClientInvoicesRequest) GetSorting() []components.ClientInvoiceSortProperty {
	if c == nil {
		return nil
	}
	return c.Sorting
}

type ClientInvoicesListClientInvoicesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ListResourceClientInvoiceSchema *components.ListResourceClientInvoiceSchema

	Next func() (*ClientInvoicesListClientInvoicesResponse, error)
}

func (c *ClientInvoicesListClientInvoicesResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClientInvoicesListClientInvoicesResponse) GetListResourceClientInvoiceSchema() *components.ListResourceClientInvoiceSchema {
	if c == nil {
		return nil
	}
	return c.ListResourceClientInvoiceSchema
}
