// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"app.spairehq.com/go/models/components"
)

type ClientInvoicesSendClientInvoiceRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (c *ClientInvoicesSendClientInvoiceRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

type ClientInvoicesSendClientInvoiceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ClientInvoiceSchema *components.ClientInvoiceSchema
}

func (c *ClientInvoicesSendClientInvoiceResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ClientInvoicesSendClientInvoiceResponse) GetClientInvoiceSchema() *components.ClientInvoiceSchema {
	if c == nil {
		return nil
	}
	return c.ClientInvoiceSchema
}
