// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"app.spairehq.com/go/models/components"
)

type CustomerPortalMembersListMembersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseCustomerPortalMembersListMembers []components.CustomerPortalMember
}

func (c *CustomerPortalMembersListMembersResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CustomerPortalMembersListMembersResponse) GetResponseCustomerPortalMembersListMembers() []components.CustomerPortalMember {
	if c == nil {
		return nil
	}
	return c.ResponseCustomerPortalMembersListMembers
}
