// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"app.spairehq.com/go/models/components"
)

type ProductsProductsPreviewTaxResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ProductTaxPreviewResponse *components.ProductTaxPreviewResponse
}

func (p *ProductsProductsPreviewTaxResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *ProductsProductsPreviewTaxResponse) GetProductTaxPreviewResponse() *components.ProductTaxPreviewResponse {
	if p == nil {
		return nil
	}
	return p.ProductTaxPreviewResponse
}
