// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"app.spairehq.com/go/internal/utils"
	"time"
)

type ClientInvoiceLineItemSchema struct {
	// The ID of the object.
	ID string `json:"id"`
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt          *time.Time `json:"modified_at"`
	ClientInvoiceID     string     `json:"client_invoice_id"`
	StripeInvoiceItemID *string    `json:"stripe_invoice_item_id"`
	Description         string     `json:"description"`
	Quantity            int64      `json:"quantity"`
	UnitAmount          int64      `json:"unit_amount"`
	Currency            string     `json:"currency"`
	Amount              int64      `json:"amount"`
	TaxAmount           int64      `json:"tax_amount"`
}

func (c ClientInvoiceLineItemSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientInvoiceLineItemSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientInvoiceLineItemSchema) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *ClientInvoiceLineItemSchema) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *ClientInvoiceLineItemSchema) GetModifiedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.ModifiedAt
}

func (c *ClientInvoiceLineItemSchema) GetClientInvoiceID() string {
	if c == nil {
		return ""
	}
	return c.ClientInvoiceID
}

func (c *ClientInvoiceLineItemSchema) GetStripeInvoiceItemID() *string {
	if c == nil {
		return nil
	}
	return c.StripeInvoiceItemID
}

func (c *ClientInvoiceLineItemSchema) GetDescription() string {
	if c == nil {
		return ""
	}
	return c.Description
}

func (c *ClientInvoiceLineItemSchema) GetQuantity() int64 {
	if c == nil {
		return 0
	}
	return c.Quantity
}

func (c *ClientInvoiceLineItemSchema) GetUnitAmount() int64 {
	if c == nil {
		return 0
	}
	return c.UnitAmount
}

func (c *ClientInvoiceLineItemSchema) GetCurrency() string {
	if c == nil {
		return ""
	}
	return c.Currency
}

func (c *ClientInvoiceLineItemSchema) GetAmount() int64 {
	if c == nil {
		return 0
	}
	return c.Amount
}

func (c *ClientInvoiceLineItemSchema) GetTaxAmount() int64 {
	if c == nil {
		return 0
	}
	return c.TaxAmount
}
