// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"app.spairehq.com/go/internal/utils"
	"app.spairehq.com/go/types"
)

// ClientInvoicePreviewRequest - Request body for generating a real-time PDF preview without persisting.
type ClientInvoicePreviewRequest struct {
	// Organization ID.
	OrganizationID string `json:"organization_id"`
	// Optional customer ID to pull name/address from.
	CustomerID *string `json:"customer_id,omitempty"`
	// ISO 4217 currency code.
	Currency string `json:"currency"`
	// Invoice line items.
	LineItems          []ClientInvoiceLineItemPreview `json:"line_items"`
	DueDate            *types.Date                    `json:"due_date,omitempty"`
	Memo               *string                        `json:"memo,omitempty"`
	PoNumber           *string                        `json:"po_number,omitempty"`
	OnBehalfOfLabel    *string                        `json:"on_behalf_of_label,omitempty"`
	DiscountAmount     *int64                         `default:"0" json:"discount_amount"`
	DiscountLabel      *string                        `json:"discount_label,omitempty"`
	IncludePaymentLink *bool                          `default:"true" json:"include_payment_link"`
	CheckoutLinkURL    *string                        `json:"checkout_link_url,omitempty"`
	// Whether to show the organization logo on the PDF.
	ShowLogo *bool `default:"true" json:"show_logo"`
	// Whether to show 'via spaire' label under the logo.
	ShowMorAttribution *bool   `default:"true" json:"show_mor_attribution"`
	BillingName        *string `json:"billing_name,omitempty"`
	BillingLine1       *string `json:"billing_line1,omitempty"`
	BillingLine2       *string `json:"billing_line2,omitempty"`
	BillingCity        *string `json:"billing_city,omitempty"`
	BillingState       *string `json:"billing_state,omitempty"`
	BillingPostalCode  *string `json:"billing_postal_code,omitempty"`
	BillingCountry     *string `json:"billing_country,omitempty"`
}

func (c ClientInvoicePreviewRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientInvoicePreviewRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientInvoicePreviewRequest) GetOrganizationID() string {
	if c == nil {
		return ""
	}
	return c.OrganizationID
}

func (c *ClientInvoicePreviewRequest) GetCustomerID() *string {
	if c == nil {
		return nil
	}
	return c.CustomerID
}

func (c *ClientInvoicePreviewRequest) GetCurrency() string {
	if c == nil {
		return ""
	}
	return c.Currency
}

func (c *ClientInvoicePreviewRequest) GetLineItems() []ClientInvoiceLineItemPreview {
	if c == nil {
		return []ClientInvoiceLineItemPreview{}
	}
	return c.LineItems
}

func (c *ClientInvoicePreviewRequest) GetDueDate() *types.Date {
	if c == nil {
		return nil
	}
	return c.DueDate
}

func (c *ClientInvoicePreviewRequest) GetMemo() *string {
	if c == nil {
		return nil
	}
	return c.Memo
}

func (c *ClientInvoicePreviewRequest) GetPoNumber() *string {
	if c == nil {
		return nil
	}
	return c.PoNumber
}

func (c *ClientInvoicePreviewRequest) GetOnBehalfOfLabel() *string {
	if c == nil {
		return nil
	}
	return c.OnBehalfOfLabel
}

func (c *ClientInvoicePreviewRequest) GetDiscountAmount() *int64 {
	if c == nil {
		return nil
	}
	return c.DiscountAmount
}

func (c *ClientInvoicePreviewRequest) GetDiscountLabel() *string {
	if c == nil {
		return nil
	}
	return c.DiscountLabel
}

func (c *ClientInvoicePreviewRequest) GetIncludePaymentLink() *bool {
	if c == nil {
		return nil
	}
	return c.IncludePaymentLink
}

func (c *ClientInvoicePreviewRequest) GetCheckoutLinkURL() *string {
	if c == nil {
		return nil
	}
	return c.CheckoutLinkURL
}

func (c *ClientInvoicePreviewRequest) GetShowLogo() *bool {
	if c == nil {
		return nil
	}
	return c.ShowLogo
}

func (c *ClientInvoicePreviewRequest) GetShowMorAttribution() *bool {
	if c == nil {
		return nil
	}
	return c.ShowMorAttribution
}

func (c *ClientInvoicePreviewRequest) GetBillingName() *string {
	if c == nil {
		return nil
	}
	return c.BillingName
}

func (c *ClientInvoicePreviewRequest) GetBillingLine1() *string {
	if c == nil {
		return nil
	}
	return c.BillingLine1
}

func (c *ClientInvoicePreviewRequest) GetBillingLine2() *string {
	if c == nil {
		return nil
	}
	return c.BillingLine2
}

func (c *ClientInvoicePreviewRequest) GetBillingCity() *string {
	if c == nil {
		return nil
	}
	return c.BillingCity
}

func (c *ClientInvoicePreviewRequest) GetBillingState() *string {
	if c == nil {
		return nil
	}
	return c.BillingState
}

func (c *ClientInvoicePreviewRequest) GetBillingPostalCode() *string {
	if c == nil {
		return nil
	}
	return c.BillingPostalCode
}

func (c *ClientInvoicePreviewRequest) GetBillingCountry() *string {
	if c == nil {
		return nil
	}
	return c.BillingCountry
}
