// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ClientInvoiceStatus string

const (
	ClientInvoiceStatusDraft         ClientInvoiceStatus = "draft"
	ClientInvoiceStatusOpen          ClientInvoiceStatus = "open"
	ClientInvoiceStatusPaid          ClientInvoiceStatus = "paid"
	ClientInvoiceStatusVoid          ClientInvoiceStatus = "void"
	ClientInvoiceStatusUncollectible ClientInvoiceStatus = "uncollectible"
)

func (e ClientInvoiceStatus) ToPointer() *ClientInvoiceStatus {
	return &e
}
func (e *ClientInvoiceStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "draft":
		fallthrough
	case "open":
		fallthrough
	case "paid":
		fallthrough
	case "void":
		fallthrough
	case "uncollectible":
		*e = ClientInvoiceStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ClientInvoiceStatus: %v", v)
	}
}
