// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"app.spairehq.com/go/internal/utils"
	"app.spairehq.com/go/types"
	"time"
)

type ClientInvoiceSchema struct {
	// The ID of the object.
	ID string `json:"id"`
	// Creation timestamp of the object.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp of the object.
	ModifiedAt             *time.Time                    `json:"modified_at"`
	OrganizationID         string                        `json:"organization_id"`
	CustomerID             string                        `json:"customer_id"`
	StripeInvoiceID        *string                       `json:"stripe_invoice_id"`
	Status                 ClientInvoiceStatus           `json:"status"`
	Currency               string                        `json:"currency"`
	SubtotalAmount         int64                         `json:"subtotal_amount"`
	DiscountAmount         int64                         `json:"discount_amount"`
	TaxAmount              int64                         `json:"tax_amount"`
	TotalAmount            int64                         `json:"total_amount"`
	Memo                   *string                       `json:"memo"`
	PoNumber               *string                       `json:"po_number"`
	DueDate                *types.Date                   `json:"due_date"`
	OnBehalfOfLabel        *string                       `json:"on_behalf_of_label"`
	DiscountLabel          *string                       `json:"discount_label"`
	IncludePaymentLink     bool                          `json:"include_payment_link"`
	ShowLogo               bool                          `json:"show_logo"`
	ShowMorAttribution     bool                          `json:"show_mor_attribution"`
	StripeHostedInvoiceURL *string                       `json:"stripe_hosted_invoice_url"`
	InvoicePdfURL          *string                       `json:"invoice_pdf_url"`
	CheckoutLink           *string                       `json:"checkout_link"`
	UserMetadata           map[string]any                `json:"user_metadata"`
	OrderID                *string                       `json:"order_id"`
	LineItems              []ClientInvoiceLineItemSchema `json:"line_items,omitempty"`
}

func (c ClientInvoiceSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientInvoiceSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientInvoiceSchema) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *ClientInvoiceSchema) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *ClientInvoiceSchema) GetModifiedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.ModifiedAt
}

func (c *ClientInvoiceSchema) GetOrganizationID() string {
	if c == nil {
		return ""
	}
	return c.OrganizationID
}

func (c *ClientInvoiceSchema) GetCustomerID() string {
	if c == nil {
		return ""
	}
	return c.CustomerID
}

func (c *ClientInvoiceSchema) GetStripeInvoiceID() *string {
	if c == nil {
		return nil
	}
	return c.StripeInvoiceID
}

func (c *ClientInvoiceSchema) GetStatus() ClientInvoiceStatus {
	if c == nil {
		return ClientInvoiceStatus("")
	}
	return c.Status
}

func (c *ClientInvoiceSchema) GetCurrency() string {
	if c == nil {
		return ""
	}
	return c.Currency
}

func (c *ClientInvoiceSchema) GetSubtotalAmount() int64 {
	if c == nil {
		return 0
	}
	return c.SubtotalAmount
}

func (c *ClientInvoiceSchema) GetDiscountAmount() int64 {
	if c == nil {
		return 0
	}
	return c.DiscountAmount
}

func (c *ClientInvoiceSchema) GetTaxAmount() int64 {
	if c == nil {
		return 0
	}
	return c.TaxAmount
}

func (c *ClientInvoiceSchema) GetTotalAmount() int64 {
	if c == nil {
		return 0
	}
	return c.TotalAmount
}

func (c *ClientInvoiceSchema) GetMemo() *string {
	if c == nil {
		return nil
	}
	return c.Memo
}

func (c *ClientInvoiceSchema) GetPoNumber() *string {
	if c == nil {
		return nil
	}
	return c.PoNumber
}

func (c *ClientInvoiceSchema) GetDueDate() *types.Date {
	if c == nil {
		return nil
	}
	return c.DueDate
}

func (c *ClientInvoiceSchema) GetOnBehalfOfLabel() *string {
	if c == nil {
		return nil
	}
	return c.OnBehalfOfLabel
}

func (c *ClientInvoiceSchema) GetDiscountLabel() *string {
	if c == nil {
		return nil
	}
	return c.DiscountLabel
}

func (c *ClientInvoiceSchema) GetIncludePaymentLink() bool {
	if c == nil {
		return false
	}
	return c.IncludePaymentLink
}

func (c *ClientInvoiceSchema) GetShowLogo() bool {
	if c == nil {
		return false
	}
	return c.ShowLogo
}

func (c *ClientInvoiceSchema) GetShowMorAttribution() bool {
	if c == nil {
		return false
	}
	return c.ShowMorAttribution
}

func (c *ClientInvoiceSchema) GetStripeHostedInvoiceURL() *string {
	if c == nil {
		return nil
	}
	return c.StripeHostedInvoiceURL
}

func (c *ClientInvoiceSchema) GetInvoicePdfURL() *string {
	if c == nil {
		return nil
	}
	return c.InvoicePdfURL
}

func (c *ClientInvoiceSchema) GetCheckoutLink() *string {
	if c == nil {
		return nil
	}
	return c.CheckoutLink
}

func (c *ClientInvoiceSchema) GetUserMetadata() map[string]any {
	if c == nil {
		return nil
	}
	return c.UserMetadata
}

func (c *ClientInvoiceSchema) GetOrderID() *string {
	if c == nil {
		return nil
	}
	return c.OrderID
}

func (c *ClientInvoiceSchema) GetLineItems() []ClientInvoiceLineItemSchema {
	if c == nil {
		return nil
	}
	return c.LineItems
}
