// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"app.spairehq.com/go/internal/utils"
)

// ClientInvoiceLineItemPreview - Relaxed line item for preview — allows zero amounts for in-progress editing.
type ClientInvoiceLineItemPreview struct {
	// Line item description.
	Description *string `default:"—" json:"description"`
	// Quantity.
	Quantity *int64 `default:"1" json:"quantity"`
	// Unit price in cents (0 allowed for preview).
	UnitAmount *int64 `default:"0" json:"unit_amount"`
}

func (c ClientInvoiceLineItemPreview) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientInvoiceLineItemPreview) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientInvoiceLineItemPreview) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *ClientInvoiceLineItemPreview) GetQuantity() *int64 {
	if c == nil {
		return nil
	}
	return c.Quantity
}

func (c *ClientInvoiceLineItemPreview) GetUnitAmount() *int64 {
	if c == nil {
		return nil
	}
	return c.UnitAmount
}
