// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ClientInvoiceSortProperty string

const (
	ClientInvoiceSortPropertyCreatedAt        ClientInvoiceSortProperty = "created_at"
	ClientInvoiceSortPropertyMinusCreatedAt   ClientInvoiceSortProperty = "-created_at"
	ClientInvoiceSortPropertyStatus           ClientInvoiceSortProperty = "status"
	ClientInvoiceSortPropertyMinusStatus      ClientInvoiceSortProperty = "-status"
	ClientInvoiceSortPropertyTotalAmount      ClientInvoiceSortProperty = "total_amount"
	ClientInvoiceSortPropertyMinusTotalAmount ClientInvoiceSortProperty = "-total_amount"
	ClientInvoiceSortPropertyDueDate          ClientInvoiceSortProperty = "due_date"
	ClientInvoiceSortPropertyMinusDueDate     ClientInvoiceSortProperty = "-due_date"
)

func (e ClientInvoiceSortProperty) ToPointer() *ClientInvoiceSortProperty {
	return &e
}
func (e *ClientInvoiceSortProperty) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "status":
		fallthrough
	case "-status":
		fallthrough
	case "total_amount":
		fallthrough
	case "-total_amount":
		fallthrough
	case "due_date":
		fallthrough
	case "-due_date":
		*e = ClientInvoiceSortProperty(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ClientInvoiceSortProperty: %v", v)
	}
}
