// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"app.spairehq.com/go/internal/utils"
)

type ClientInvoiceLineItemCreate struct {
	// Line item description shown on the invoice.
	Description string `json:"description"`
	// Quantity.
	Quantity *int64 `default:"1" json:"quantity"`
	// Unit price in the smallest currency unit (e.g. cents).
	UnitAmount int64 `json:"unit_amount"`
}

func (c ClientInvoiceLineItemCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientInvoiceLineItemCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientInvoiceLineItemCreate) GetDescription() string {
	if c == nil {
		return ""
	}
	return c.Description
}

func (c *ClientInvoiceLineItemCreate) GetQuantity() *int64 {
	if c == nil {
		return nil
	}
	return c.Quantity
}

func (c *ClientInvoiceLineItemCreate) GetUnitAmount() int64 {
	if c == nil {
		return 0
	}
	return c.UnitAmount
}
