// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"app.spairehq.com/go/internal/utils"
	"app.spairehq.com/go/types"
)

type ClientInvoiceCreate struct {
	// ID of the Spaire customer to invoice.
	CustomerID string `json:"customer_id"`
	// ISO 4217 currency code (e.g. 'usd').
	Currency string `json:"currency"`
	// Invoice line items. At least one required.
	LineItems []ClientInvoiceLineItemCreate `json:"line_items"`
	// Payment due date. Determines days_until_due on the Stripe invoice.
	DueDate *types.Date `json:"due_date,omitempty"`
	// Internal memo / invoice description.
	Memo *string `json:"memo,omitempty"`
	// Purchase order number.
	PoNumber *string `json:"po_number,omitempty"`
	// Name shown in 'on behalf of' display on the invoice. Defaults to the organization name.
	OnBehalfOfLabel *string `json:"on_behalf_of_label,omitempty"`
	// Flat discount amount in the smallest currency unit (e.g. cents). Applied before tax.
	DiscountAmount *int64 `default:"0" json:"discount_amount"`
	// Label shown for the discount line on the invoice (e.g. 'Promo code').
	DiscountLabel *string `json:"discount_label,omitempty"`
	// Whether to include a hosted payment link in the invoice email.
	IncludePaymentLink *bool `default:"true" json:"include_payment_link"`
	// Whether to show the organization logo on the PDF.
	ShowLogo *bool `default:"true" json:"show_logo"`
	// Whether to show 'via spaire' label under the logo.
	ShowMorAttribution *bool `default:"true" json:"show_mor_attribution"`
	// Arbitrary key-value metadata to attach to the invoice.
	UserMetadata map[string]any `json:"user_metadata,omitempty"`
}

func (c ClientInvoiceCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClientInvoiceCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClientInvoiceCreate) GetCustomerID() string {
	if c == nil {
		return ""
	}
	return c.CustomerID
}

func (c *ClientInvoiceCreate) GetCurrency() string {
	if c == nil {
		return ""
	}
	return c.Currency
}

func (c *ClientInvoiceCreate) GetLineItems() []ClientInvoiceLineItemCreate {
	if c == nil {
		return []ClientInvoiceLineItemCreate{}
	}
	return c.LineItems
}

func (c *ClientInvoiceCreate) GetDueDate() *types.Date {
	if c == nil {
		return nil
	}
	return c.DueDate
}

func (c *ClientInvoiceCreate) GetMemo() *string {
	if c == nil {
		return nil
	}
	return c.Memo
}

func (c *ClientInvoiceCreate) GetPoNumber() *string {
	if c == nil {
		return nil
	}
	return c.PoNumber
}

func (c *ClientInvoiceCreate) GetOnBehalfOfLabel() *string {
	if c == nil {
		return nil
	}
	return c.OnBehalfOfLabel
}

func (c *ClientInvoiceCreate) GetDiscountAmount() *int64 {
	if c == nil {
		return nil
	}
	return c.DiscountAmount
}

func (c *ClientInvoiceCreate) GetDiscountLabel() *string {
	if c == nil {
		return nil
	}
	return c.DiscountLabel
}

func (c *ClientInvoiceCreate) GetIncludePaymentLink() *bool {
	if c == nil {
		return nil
	}
	return c.IncludePaymentLink
}

func (c *ClientInvoiceCreate) GetShowLogo() *bool {
	if c == nil {
		return nil
	}
	return c.ShowLogo
}

func (c *ClientInvoiceCreate) GetShowMorAttribution() *bool {
	if c == nil {
		return nil
	}
	return c.ShowMorAttribution
}

func (c *ClientInvoiceCreate) GetUserMetadata() map[string]any {
	if c == nil {
		return nil
	}
	return c.UserMetadata
}
