// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListResourceClientInvoiceSchema struct {
	Items      []ClientInvoiceSchema `json:"items"`
	Pagination Pagination            `json:"pagination"`
}

func (l *ListResourceClientInvoiceSchema) GetItems() []ClientInvoiceSchema {
	if l == nil {
		return []ClientInvoiceSchema{}
	}
	return l.Items
}

func (l *ListResourceClientInvoiceSchema) GetPagination() Pagination {
	if l == nil {
		return Pagination{}
	}
	return l.Pagination
}
