// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"app.spairehq.com/go/internal/utils"
)

type OrganizationFeatureSettings struct {
	// If this organization has issue funding enabled
	IssueFundingEnabled *bool `default:"false" json:"issue_funding_enabled"`
	// If this organization has seat-based pricing enabled
	SeatBasedPricingEnabled *bool `default:"false" json:"seat_based_pricing_enabled"`
	// If this organization has RevOps enabled
	RevopsEnabled *bool `default:"false" json:"revops_enabled"`
	// If this organization has Wallets enabled
	WalletsEnabled *bool `default:"false" json:"wallets_enabled"`
	// If this organization has the Member model enabled
	MemberModelEnabled *bool `default:"false" json:"member_model_enabled"`
	// If this organization reads from Tinybird
	TinybirdRead *bool `default:"false" json:"tinybird_read"`
	// If this organization compares Tinybird results with database
	TinybirdCompare *bool `default:"false" json:"tinybird_compare"`
	// If this organization has unlocked the Startup Stack perks by completing their first sale
	PerksUnlocked *bool `default:"false" json:"perks_unlocked"`
}

func (o OrganizationFeatureSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationFeatureSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationFeatureSettings) GetIssueFundingEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.IssueFundingEnabled
}

func (o *OrganizationFeatureSettings) GetSeatBasedPricingEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.SeatBasedPricingEnabled
}

func (o *OrganizationFeatureSettings) GetRevopsEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.RevopsEnabled
}

func (o *OrganizationFeatureSettings) GetWalletsEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.WalletsEnabled
}

func (o *OrganizationFeatureSettings) GetMemberModelEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.MemberModelEnabled
}

func (o *OrganizationFeatureSettings) GetTinybirdRead() *bool {
	if o == nil {
		return nil
	}
	return o.TinybirdRead
}

func (o *OrganizationFeatureSettings) GetTinybirdCompare() *bool {
	if o == nil {
		return nil
	}
	return o.TinybirdCompare
}

func (o *OrganizationFeatureSettings) GetPerksUnlocked() *bool {
	if o == nil {
		return nil
	}
	return o.PerksUnlocked
}
