// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"app.spairehq.com/go/internal/utils"
	"encoding/json"
	"fmt"
)

// ThumbnailSize - Product thumbnail size
type ThumbnailSize string

const (
	ThumbnailSizeSmall  ThumbnailSize = "small"
	ThumbnailSizeMedium ThumbnailSize = "medium"
	ThumbnailSizeLarge  ThumbnailSize = "large"
)

func (e ThumbnailSize) ToPointer() *ThumbnailSize {
	return &e
}
func (e *ThumbnailSize) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "small":
		fallthrough
	case "medium":
		fallthrough
	case "large":
		*e = ThumbnailSize(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ThumbnailSize: %v", v)
	}
}

type OrganizationStorefrontSettings struct {
	// Whether the storefront is enabled
	Enabled *bool `default:"false" json:"enabled"`
	// Show the storefront header/banner
	ShowHeader *bool `default:"true" json:"show_header"`
	// URL of the storefront header/banner image
	HeaderImageURL *string `json:"header_image_url,omitempty"`
	// Show the organization logo
	ShowLogo *bool `default:"true" json:"show_logo"`
	// Show the organization name
	ShowName *bool `default:"true" json:"show_name"`
	// Show the storefront description
	ShowDescription *bool `default:"true" json:"show_description"`
	// Storefront description
	Description *string `json:"description,omitempty"`
	// Product thumbnail size
	ThumbnailSize *ThumbnailSize `default:"medium" json:"thumbnail_size"`
	// Show product details (name, price)
	ShowProductDetails *bool `default:"true" json:"show_product_details"`
	// Profile title (e.g. Designer, 3D Artist)
	ProfileTitle *string `json:"profile_title,omitempty"`
	// Skill/expertise tags displayed on the profile
	Skills []string `json:"skills,omitempty"`
	// Languages spoken
	Languages []string `json:"languages,omitempty"`
	// Show 'Available for work' badge on the profile
	AvailableForWork *bool `default:"false" json:"available_for_work"`
	// Product IDs to feature on the storefront (empty = show all)
	FeaturedProductIds []string `json:"featured_product_ids,omitempty"`
}

func (o OrganizationStorefrontSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationStorefrontSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationStorefrontSettings) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *OrganizationStorefrontSettings) GetShowHeader() *bool {
	if o == nil {
		return nil
	}
	return o.ShowHeader
}

func (o *OrganizationStorefrontSettings) GetHeaderImageURL() *string {
	if o == nil {
		return nil
	}
	return o.HeaderImageURL
}

func (o *OrganizationStorefrontSettings) GetShowLogo() *bool {
	if o == nil {
		return nil
	}
	return o.ShowLogo
}

func (o *OrganizationStorefrontSettings) GetShowName() *bool {
	if o == nil {
		return nil
	}
	return o.ShowName
}

func (o *OrganizationStorefrontSettings) GetShowDescription() *bool {
	if o == nil {
		return nil
	}
	return o.ShowDescription
}

func (o *OrganizationStorefrontSettings) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *OrganizationStorefrontSettings) GetThumbnailSize() *ThumbnailSize {
	if o == nil {
		return nil
	}
	return o.ThumbnailSize
}

func (o *OrganizationStorefrontSettings) GetShowProductDetails() *bool {
	if o == nil {
		return nil
	}
	return o.ShowProductDetails
}

func (o *OrganizationStorefrontSettings) GetProfileTitle() *string {
	if o == nil {
		return nil
	}
	return o.ProfileTitle
}

func (o *OrganizationStorefrontSettings) GetSkills() []string {
	if o == nil {
		return nil
	}
	return o.Skills
}

func (o *OrganizationStorefrontSettings) GetLanguages() []string {
	if o == nil {
		return nil
	}
	return o.Languages
}

func (o *OrganizationStorefrontSettings) GetAvailableForWork() *bool {
	if o == nil {
		return nil
	}
	return o.AvailableForWork
}

func (o *OrganizationStorefrontSettings) GetFeaturedProductIds() []string {
	if o == nil {
		return nil
	}
	return o.FeaturedProductIds
}
