// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"app.spairehq.com/go/internal/utils"
	"encoding/json"
	"fmt"
)

type SwitchingFrom string

const (
	SwitchingFromPaddle       SwitchingFrom = "paddle"
	SwitchingFromLemonSqueezy SwitchingFrom = "lemon_squeezy"
	SwitchingFromGumroad      SwitchingFrom = "gumroad"
	SwitchingFromStripe       SwitchingFrom = "stripe"
	SwitchingFromOther        SwitchingFrom = "other"
)

func (e SwitchingFrom) ToPointer() *SwitchingFrom {
	return &e
}
func (e *SwitchingFrom) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "paddle":
		fallthrough
	case "lemon_squeezy":
		fallthrough
	case "gumroad":
		fallthrough
	case "stripe":
		fallthrough
	case "other":
		*e = SwitchingFrom(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SwitchingFrom: %v", v)
	}
}

type OrganizationDetails struct {
	// Brief information about you and your business.
	About *string `default:"" json:"about"`
	// Description of digital products being sold.
	ProductDescription string `json:"product_description"`
	// How the organization will integrate and use Spaire.
	IntendedUse *string `default:"" json:"intended_use"`
	// Main customer acquisition channels.
	CustomerAcquisition []string `json:"customer_acquisition,omitempty"`
	// Estimated revenue in the next 12 months
	FutureAnnualRevenue *int64 `default:"0" json:"future_annual_revenue"`
	// Switching from another platform?
	Switching *bool `default:"true" json:"switching"`
	// Which platform the organization is migrating from.
	SwitchingFrom *SwitchingFrom `json:"switching_from,omitempty"`
	// Revenue from last year if applicable.
	PreviousAnnualRevenue *int64 `default:"0" json:"previous_annual_revenue"`
}

func (o OrganizationDetails) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationDetails) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationDetails) GetAbout() *string {
	if o == nil {
		return nil
	}
	return o.About
}

func (o *OrganizationDetails) GetProductDescription() string {
	if o == nil {
		return ""
	}
	return o.ProductDescription
}

func (o *OrganizationDetails) GetIntendedUse() *string {
	if o == nil {
		return nil
	}
	return o.IntendedUse
}

func (o *OrganizationDetails) GetCustomerAcquisition() []string {
	if o == nil {
		return nil
	}
	return o.CustomerAcquisition
}

func (o *OrganizationDetails) GetFutureAnnualRevenue() *int64 {
	if o == nil {
		return nil
	}
	return o.FutureAnnualRevenue
}

func (o *OrganizationDetails) GetSwitching() *bool {
	if o == nil {
		return nil
	}
	return o.Switching
}

func (o *OrganizationDetails) GetSwitchingFrom() *SwitchingFrom {
	if o == nil {
		return nil
	}
	return o.SwitchingFrom
}

func (o *OrganizationDetails) GetPreviousAnnualRevenue() *int64 {
	if o == nil {
		return nil
	}
	return o.PreviousAnnualRevenue
}
