// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ProductTaxPreviewResponse - Tax preview result for a product price.
type ProductTaxPreviewResponse struct {
	Subtotal         int64           `json:"subtotal"`
	TaxAmount        int64           `json:"tax_amount"`
	Total            int64           `json:"total"`
	Currency         string          `json:"currency"`
	Quantity         int64           `json:"quantity"`
	TaxRate          *TaxRatePreview `json:"tax_rate,omitempty"`
	TaxabilityReason *string         `json:"taxability_reason,omitempty"`
}

func (p *ProductTaxPreviewResponse) GetSubtotal() int64 {
	if p == nil {
		return 0
	}
	return p.Subtotal
}

func (p *ProductTaxPreviewResponse) GetTaxAmount() int64 {
	if p == nil {
		return 0
	}
	return p.TaxAmount
}

func (p *ProductTaxPreviewResponse) GetTotal() int64 {
	if p == nil {
		return 0
	}
	return p.Total
}

func (p *ProductTaxPreviewResponse) GetCurrency() string {
	if p == nil {
		return ""
	}
	return p.Currency
}

func (p *ProductTaxPreviewResponse) GetQuantity() int64 {
	if p == nil {
		return 0
	}
	return p.Quantity
}

func (p *ProductTaxPreviewResponse) GetTaxRate() *TaxRatePreview {
	if p == nil {
		return nil
	}
	return p.TaxRate
}

func (p *ProductTaxPreviewResponse) GetTaxabilityReason() *string {
	if p == nil {
		return nil
	}
	return p.TaxabilityReason
}
