// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"app.spairehq.com/go/internal/utils"
)

// ProductTaxPreviewRequest - Request body for previewing tax on a product price.
type ProductTaxPreviewRequest struct {
	// Amount in smallest currency unit (e.g. cents for USD).
	Amount int64 `json:"amount"`
	// ISO 4217 currency code (e.g. 'usd').
	Currency string `json:"currency"`
	// ISO 3166-1 alpha-2 country code (e.g. 'AU').
	Country string `json:"country"`
	// Unit quantity for the preview calculation.
	Quantity *int64 `default:"1" json:"quantity"`
	// State/province code for US/CA (e.g. 'WA' or 'US-WA').
	State *string `json:"state,omitempty"`
}

func (p ProductTaxPreviewRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProductTaxPreviewRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *ProductTaxPreviewRequest) GetAmount() int64 {
	if p == nil {
		return 0
	}
	return p.Amount
}

func (p *ProductTaxPreviewRequest) GetCurrency() string {
	if p == nil {
		return ""
	}
	return p.Currency
}

func (p *ProductTaxPreviewRequest) GetCountry() string {
	if p == nil {
		return ""
	}
	return p.Country
}

func (p *ProductTaxPreviewRequest) GetQuantity() *int64 {
	if p == nil {
		return nil
	}
	return p.Quantity
}

func (p *ProductTaxPreviewRequest) GetState() *string {
	if p == nil {
		return nil
	}
	return p.State
}
