// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"app.spairehq.com/go/internal/utils"
)

// ProductPriceFixedCreate - Schema to create a fixed price.
type ProductPriceFixedCreate struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	amountType    string               `const:"fixed" json:"amount_type"`
	PriceCurrency *PresentmentCurrency `json:"price_currency,omitempty"`
	// The tax behavior of the price. If not set, it will default to the organization's default tax behavior.
	TaxBehavior *TaxBehaviorOption `json:"tax_behavior,omitempty"`
	// The price in cents.
	PriceAmount int64 `json:"price_amount"`
}

func (p ProductPriceFixedCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProductPriceFixedCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"amount_type", "price_amount"}); err != nil {
		return err
	}
	return nil
}

func (p *ProductPriceFixedCreate) GetAmountType() string {
	return "fixed"
}

func (p *ProductPriceFixedCreate) GetPriceCurrency() *PresentmentCurrency {
	if p == nil {
		return nil
	}
	return p.PriceCurrency
}

func (p *ProductPriceFixedCreate) GetTaxBehavior() *TaxBehaviorOption {
	if p == nil {
		return nil
	}
	return p.TaxBehavior
}

func (p *ProductPriceFixedCreate) GetPriceAmount() int64 {
	if p == nil {
		return 0
	}
	return p.PriceAmount
}
