// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/polarsource/polar-go/internal/utils"
)

// ProductPriceSeatBasedCreate - Schema to create a seat-based price.
type ProductPriceSeatBasedCreate struct {
	amountType string `const:"seat_based" json:"amount_type"`
	// The currency. Currently, only `usd` is supported.
	PriceCurrency *string `default:"usd" json:"price_currency"`
	// The price per seat in cents.
	PricePerSeat int64 `json:"price_per_seat"`
}

func (p ProductPriceSeatBasedCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProductPriceSeatBasedCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"amount_type", "price_per_seat"}); err != nil {
		return err
	}
	return nil
}

func (p *ProductPriceSeatBasedCreate) GetAmountType() string {
	return "seat_based"
}

func (p *ProductPriceSeatBasedCreate) GetPriceCurrency() *string {
	if p == nil {
		return nil
	}
	return p.PriceCurrency
}

func (p *ProductPriceSeatBasedCreate) GetPricePerSeat() int64 {
	if p == nil {
		return 0
	}
	return p.PricePerSeat
}
