// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"app.spairehq.com/go/internal/utils"
)

// StorefrontHeaderFileCreate - Schema to create a file to be used as a storefront header/banner image.
type StorefrontHeaderFileCreate struct {
	OrganizationID *string `json:"organization_id,omitempty"`
	Name           string  `json:"name"`
	// MIME type of the file. Only images are supported for this type of file.
	MimeType string `json:"mime_type"`
	// Size of the file. A maximum of 10 MB is allowed for this type of file.
	Size                 int64                 `json:"size"`
	ChecksumSha256Base64 *string               `json:"checksum_sha256_base64,omitempty"`
	Upload               S3FileCreateMultipart `json:"upload"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	service string  `const:"storefront_header" json:"service"`
	Version *string `json:"version,omitempty"`
}

func (s StorefrontHeaderFileCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StorefrontHeaderFileCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"name", "mime_type", "size", "upload", "service"}); err != nil {
		return err
	}
	return nil
}

func (s *StorefrontHeaderFileCreate) GetOrganizationID() *string {
	if s == nil {
		return nil
	}
	return s.OrganizationID
}

func (s *StorefrontHeaderFileCreate) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *StorefrontHeaderFileCreate) GetMimeType() string {
	if s == nil {
		return ""
	}
	return s.MimeType
}

func (s *StorefrontHeaderFileCreate) GetSize() int64 {
	if s == nil {
		return 0
	}
	return s.Size
}

func (s *StorefrontHeaderFileCreate) GetChecksumSha256Base64() *string {
	if s == nil {
		return nil
	}
	return s.ChecksumSha256Base64
}

func (s *StorefrontHeaderFileCreate) GetUpload() S3FileCreateMultipart {
	if s == nil {
		return S3FileCreateMultipart{}
	}
	return s.Upload
}

func (s *StorefrontHeaderFileCreate) GetService() string {
	return "storefront_header"
}

func (s *StorefrontHeaderFileCreate) GetVersion() *string {
	if s == nil {
		return nil
	}
	return s.Version
}
