// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"app.spairehq.com/go/internal/utils"
	"time"
)

// StorefrontHeaderFileRead - File to be used as a storefront header/banner image.
type StorefrontHeaderFileRead struct {
	// The ID of the object.
	ID                   string     `json:"id"`
	OrganizationID       string     `json:"organization_id"`
	Name                 string     `json:"name"`
	Path                 string     `json:"path"`
	MimeType             string     `json:"mime_type"`
	Size                 int64      `json:"size"`
	StorageVersion       *string    `json:"storage_version"`
	ChecksumEtag         *string    `json:"checksum_etag"`
	ChecksumSha256Base64 *string    `json:"checksum_sha256_base64"`
	ChecksumSha256Hex    *string    `json:"checksum_sha256_hex"`
	LastModifiedAt       *time.Time `json:"last_modified_at"`
	Version              *string    `json:"version"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	service      string    `const:"storefront_header" json:"service"`
	IsUploaded   bool      `json:"is_uploaded"`
	CreatedAt    time.Time `json:"created_at"`
	SizeReadable string    `json:"size_readable"`
	PublicURL    string    `json:"public_url"`
}

func (s StorefrontHeaderFileRead) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StorefrontHeaderFileRead) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"id", "organization_id", "name", "path", "mime_type", "size", "service", "is_uploaded", "created_at", "size_readable", "public_url"}); err != nil {
		return err
	}
	return nil
}

func (s *StorefrontHeaderFileRead) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *StorefrontHeaderFileRead) GetOrganizationID() string {
	if s == nil {
		return ""
	}
	return s.OrganizationID
}

func (s *StorefrontHeaderFileRead) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *StorefrontHeaderFileRead) GetPath() string {
	if s == nil {
		return ""
	}
	return s.Path
}

func (s *StorefrontHeaderFileRead) GetMimeType() string {
	if s == nil {
		return ""
	}
	return s.MimeType
}

func (s *StorefrontHeaderFileRead) GetSize() int64 {
	if s == nil {
		return 0
	}
	return s.Size
}

func (s *StorefrontHeaderFileRead) GetStorageVersion() *string {
	if s == nil {
		return nil
	}
	return s.StorageVersion
}

func (s *StorefrontHeaderFileRead) GetChecksumEtag() *string {
	if s == nil {
		return nil
	}
	return s.ChecksumEtag
}

func (s *StorefrontHeaderFileRead) GetChecksumSha256Base64() *string {
	if s == nil {
		return nil
	}
	return s.ChecksumSha256Base64
}

func (s *StorefrontHeaderFileRead) GetChecksumSha256Hex() *string {
	if s == nil {
		return nil
	}
	return s.ChecksumSha256Hex
}

func (s *StorefrontHeaderFileRead) GetLastModifiedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.LastModifiedAt
}

func (s *StorefrontHeaderFileRead) GetVersion() *string {
	if s == nil {
		return nil
	}
	return s.Version
}

func (s *StorefrontHeaderFileRead) GetService() string {
	return "storefront_header"
}

func (s *StorefrontHeaderFileRead) GetIsUploaded() bool {
	if s == nil {
		return false
	}
	return s.IsUploaded
}

func (s *StorefrontHeaderFileRead) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *StorefrontHeaderFileRead) GetSizeReadable() string {
	if s == nil {
		return ""
	}
	return s.SizeReadable
}

func (s *StorefrontHeaderFileRead) GetPublicURL() string {
	if s == nil {
		return ""
	}
	return s.PublicURL
}
