// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TaxRatePreview struct {
	DisplayName string   `json:"display_name"`
	Percentage  *float64 `json:"percentage,omitempty"`
}

func (t *TaxRatePreview) GetDisplayName() string {
	if t == nil {
		return ""
	}
	return t.DisplayName
}

func (t *TaxRatePreview) GetPercentage() *float64 {
	if t == nil {
		return nil
	}
	return t.Percentage
}
